#ifndef ZIPC_READY_LINUX_R5_SHARED_LAYOUT_H
#define ZIPC_READY_LINUX_R5_SHARED_LAYOUT_H

#include <zipc/zipc.h>

#define ZIPC_READY_SHM_BASE UINT64_C(0x70000000)
#define ZIPC_READY_SHM_SIZE (4U * 1024U * 1024U)
#define ZIPC_READY_SLOT_COUNT 32U
#define ZIPC_READY_SLOT_SIZE  (64U * 1024U)

enum {
    ZIPC_COMPONENT_LINUX_P1 = 1,
    ZIPC_COMPONENT_R5_0     = 2,
    ZIPC_COMPONENT_R5_1     = 3,
    ZIPC_COMPONENT_LINUX_P2 = 4,
};

#endif
